#cloud-config
# Cloud-init configuration for Ubuntu VM on Azure

# Ensure cloud-init is installed and updated
runcmd:
  - |-
    if ! command -v cloud-init &> /dev/null
    then
        echo "Cloud-init not found, installing..."
        apt-get update -y
        apt-get install -y cloud-init
        echo "Cloud-init installed."
    else
        echo "Cloud-init already installed."
    fi

# Update package cache and upgrade packages
package_update: true
package_upgrade: true

# Install required packages
packages:
  - curl
  - wget
  - git
  - htop
  - unzip
  - jq

# Create directories
runcmd:
  - mkdir -p /opt/cloudinit-scripts
  - mkdir -p /var/log/cloudinit-scripts

# Download and execute the main script
write_files:
  - path: /opt/cloudinit-scripts/main-script.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      # Main script executed by cloud-init
      
      LOG_FILE="/var/log/cloudinit-scripts/main-script.log"
      
      echo "$(date): Starting main script execution" >> $LOG_FILE
      
      # Download and execute the sample script
      SCRIPT_URL="https://raw.githubusercontent.com/aadil268/cloud-init/main/config/sample-script.sh"
      SCRIPT_PATH="/opt/cloudinit-scripts/sample-script.sh"
      
      echo "$(date): Downloading sample script from $SCRIPT_URL" >> $LOG_FILE
      
      if curl -s -o $SCRIPT_PATH $SCRIPT_URL; then
          chmod +x $SCRIPT_PATH
          echo "$(date): Successfully downloaded sample script" >> $LOG_FILE
          
          echo "$(date): Executing sample script" >> $LOG_FILE
          bash $SCRIPT_PATH >> $LOG_FILE 2>&1
          
          echo "$(date): Sample script execution completed with exit code: $?" >> $LOG_FILE
      else
          echo "$(date): Failed to download sample script, executing local fallback" >> $LOG_FILE
          # Fallback to local script execution
          bash /opt/cloudinit-scripts/sample-script-local.sh >> $LOG_FILE 2>&1
      fi
      
      echo "$(date): Main script execution completed" >> $LOG_FILE

  - path: /opt/cloudinit-scripts/sample-script-local.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      # Local fallback sample script
      
      echo "$(date): Executing local sample script"
      echo "$(date): System information:"
      uname -a
      echo "$(date): Disk usage:"
      df -h
      echo "$(date): Memory usage:"
      free -h
      echo "$(date): Network interfaces:"
      ip addr show
      echo "$(date): Installed packages:"
      dpkg -l | wc -l
      echo "$(date): Local sample script completed"

# Execute the main script
runcmd:
  - /opt/cloudinit-scripts/main-script.sh

# Final message
final_message: "Cloud-init setup completed successfully. Check /var/log/cloudinit-scripts/ for execution logs."

